language: dart
dart:
  - stable

dart_task:
  - test
# - dartanalyzer
# - dartfmt: -w lib/ test/

script: ./tool/cover.sh

before_install:
  - chmod -R +x ./tool

deploy:
  provider: script
  script: bash ./tool/publish.sh
  on:
    branch: master
    tags: true

cache:
  directories:
    - $HOME/.pub-cache
    - .dart_tool/build
