language: dart
dart:
 - stable

dart_task:
 - test
# - dartanalyzer
# - dartfmt: -w lib/ test/

before_install:
 - chmod +x ./tool/publish.sh

deploy:
  provider: script
  script: bash ./tool/publish.sh
  on:
    branch: master
    tags: true

cache:
  directories:
  - $HOME/.pub-cache
  - .dart_tool/build
