name: activatory
description: Test data generator for Test-Driven Development
version: 0.0.22
homepage: https://github.com/syberside/Activatory

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  uuid: ^2.0.0

dev_dependencies:
  test: ^1.0.0
  mockito: ^4.0.0
