name: activatory
description: Test data generator aimed to simplify Test-Driven Development with Dart
version: 0.0.10
homepage: https://github.com/syberside/Activatory
author: syberside

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  uuid: ^2.0.0-rc1

dev_dependencies:
  test: ^1.0.0
